port: 8010
api: {
    url: https://publish-api.planning.data.gov.uk,
    port: 8082,
    validationEndpoint: /api/dataset/validate/file/request,
    requestTimeout: 50000
}
maintenance: {
    serviceUnavailable: false,
    upTime: "9am on Monday 19 November 2024"
}
serviceName: 'Publish planning and housing data for England'
feedbackLink: 'https://docs.google.com/forms/d/e/1FAIpQLSdYXqY0Aaket9XJBiGDhSL_CD_cxHZxgvQCFZZtdURdvvIY5A/viewform'
aws: {
    region: "eu-west-2",
    uploadBucket: "dluhc-data-platform-request-files-local"
}
requestApi: {
    baseUrl: http://localhost:8000,
    requestsEndpoint: /requests,
    requestTimeout: 2000
}