name: "Build & Push Containers to Registry"
description: "Creats containerised app and pushes it to registry"
runs:
  using: 'composite'
  steps:
    - id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: aws-actions/amazon-ecr-login@v2
    - name: Pull latest image
      run: docker pull $DOCKER_REPO:latest || echo "no current latest image"
      shell: bash
    - run: docker build --build-arg DEPLOY_TIME="$(date +%Y-%m-%dT%H:%M:%S)" --build-arg GIT_COMMIT="${{ steps.vars.outputs.sha_short }}" -t $DOCKER_REPO:${{ steps.vars.outputs.sha_short }} .
      shell: bash
    - run: docker tag $DOCKER_REPO:${{ steps.vars.outputs.sha_short }} $DOCKER_REPO:latest
      shell: bash
    - run: docker push $DOCKER_REPO:${{ steps.vars.outputs.sha_short }}
      shell: bash
    - run: docker push $DOCKER_REPO:latest
      shell: bash