name: Code change pipeline
run-name: Code change pipeline to ${{ inputs.environment || 'development' }} by @${{ github.actor }}

on:
  push:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: The environment to deploy to.

jobs:  
  run-tests:
    uses: ./.github/workflows/test.yml
    with:
      environment: '${{ inputs.environment }}'
    secrets: inherit

  detect-environments:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      environments: ${{ steps.environments.outputs.result }}
    steps:
      - uses: actions/github-script@v6
        id: environments
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          result-encoding: json
          script: |
            if (context.payload?.inputs?.environment) return [context.payload?.inputs?.environment];
            const {data: {environments}} = 
              await github.request(`GET /repos/${process.env.GITHUB_REPOSITORY}/environments`);
            return environments.map(e => e.name)
  
  deploy-changes:
    needs: [detect-environments]
    # NOTE: remove the below guard once ready to merge to main
    if: ${{ github.ref_name == 'rosado/ci_cd_v2' }} 
    uses: ./.github/workflows/deploy.yml
    with:
      environment: '${{ inputs.environment }}'
    secrets: inherit

 
