name: Run Tests and Lint Files
# on: pull_request
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
              npm ci
              npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
              npm ci
              npx playwright install --with-deps
              npm run test